name: 'ContinuousIntegration'

on:
    pull_request:
    push:

jobs:
    build:
        env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        runs-on: 'ubuntu-latest'
        steps:
            - uses: 'actions/checkout@v1'
